# Makefile
#
# (c)Copyright 2017, Fresco Logic, Incorporated.
#
# Purpose:
#
# NOTE: DO NOT SEND THIS FILE OUTSIDE OF FRESCO LOGIC.
#

fl2000-y := fl2000_module.o
fl2000-y += fl2000_bulk.o
fl2000-y += fl2000_ioctl.o
fl2000-y += fl2000_render.o
fl2000-y += fl2000_dev.o
fl2000-y += fl2000_dongle.o
fl2000-y += fl2000_big_table.o
fl2000-y += fl2000_i2c.o
fl2000-y += fl2000_register.o
fl2000-y += fl2000_monitor.o
fl2000-y += fl2000_desc.o
fl2000-y += fl2000_interrupt.o
fl2000-y += fl2000_compression.o
fl2000-y += fl2000_surface.o
fl2000-y += fl2000_fops.o
fl2000-y += fl2000_hdmi.o


obj-$(CONFIG_USB_FL2000) := fl2000.o
