obj-$(CONFIG_ARCH_MANGO)	+= top/top-mango.o
obj-$(CONFIG_ARCH_SOPHGO)	+= ../bitmain/top/top_intc.o
obj-$(CONFIG_ARCH_SOPHGO)	+= ../bitmain/top/top_intc_test.o
obj-$(CONFIG_ARCH_SOPHGO)	+= ../bitmain/ion/
obj-$(CONFIG_ARCH_SOPHGO)	+= m2m_dma/m2m_dma.o
obj-$(CONFIG_ARCH_MANGO)	+= ../bitmain/tach/bm_tach.o
obj-$(CONFIG_ARCH_SOPHGO)	+= ../bitmain/efuse/bm_efuse.o
obj-$(CONFIG_ARCH_SOPHGO)	+= ../bitmain/efuse/kmemac.o

obj-$(CONFIG_PLATFORM_DRIVER_RXU)	+= rxu/rxu.o
obj-$(CONFIG_PLATFORM_DRIVER_FAU)	+= fau/fau.o
