# SPDX-License-Identifier: GPL-2.0+

dtb-$(CONFIG_ARCH_BITMAIN) += bm1880-sophon-edge.dtb

dtb-$(CONFIG_ARCH_VEXPRESS) += qemu.dtb
dtb-$(CONFIG_ARCH_BM1684) += bm1684_evb_v1.2.dtb \
				bm1684_se5_v1.1.dtb bm1684_se5_v1.1_mm0.dtb bm1684_se5_v1.1_mm1.dtb bm1684_se5_v1.1_mm2.dtb \
				bm1684_se5_v2.0.dtb bm1684_se5_v2.1.dtb bm1684_se5_v2.5.dtb bm1684_se6_ctrl.dtb \
				bm1684_sm5_v1.1_rb.dtb bm1684_sm5_v1.1_rb_mm0.dtb bm1684_sm5_v1.1_rb_mm1.dtb \
				bm1684_sm5_v1.2_rb.dtb bm1684_sm5_v1.2_tb.dtb bm1684_cust_v1.1.dtb bm1684_cust_v1.3.dtb \
				bm1684_cust_v1.4.dtb bm1684_sm5m_v3.1_rb.dtb bm1684_sm5m_v3.1_tb.dtb\
				bm1684_sm5m_v0.0_tb.dtb bm1684_sm5m_v0.1_tb.dtb bm1684_sm5m_v0.2_tb.dtb bm1684_sm5m_v3.0_tb.dtb \
				bm1684_sm5m_v0.0_rb.dtb \
				bm1684_sm5m_v0.1_rb.dtb bm1684_sm5m_v0.1_rb_mm0.dtb\
				bm1684_sm5m_v0.2_rb.dtb bm1684_sm5m_v3.0_rb.dtb \
				bm1684_sc5_ep.dtb bm1684_sc5_mix.dtb \
				bm1684x_fpga.dtb bm1684x_pld.dtb bm1684x_evb_v0.0.dtb \
				bm1684x_sm7m_v0.0.dtb bm1684x_ep.dtb bm1684x_mix.dtb \
				bm1684x_sm7_ctrl.dtb \
				bm1684x_sm7m_v0.0_cust_v1.dtb
