ccflags-y += -DCONFIG_ION_CARVEOUT_HEAP

obj-y 		+= ion.o ion-ioctl.o ion_heap.o \
		   ion_carveout_heap.o \
		   bitmain/bitmain_ion_debugfs.o \
		   bitmain/bitmain_ion_alloc.o \
		   bitmain/bitmain_ion.o
